=================================
         Console output          
=================================
OUT: Writing AlonBug_fails_p_.h ...
OUT: Writing AlonBug_fails.zing ...
OUT: Compiling AlonBug_fails.zing to AlonBug_fails.dll ...
OUT: alonbug_fails.p (8, 13): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (8, 13): inferred type:  NIL
OUT: alonbug_fails.p (8, 17): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (8, 20): inferred type:  NIL
OUT: alonbug_fails.p (8, 26): inferred type:  BaseType(EVENT)
OUT: alonbug_fails.p (10, 10): inferred type:  NIL
OUT: alonbug_fails.p (10, 18): inferred type:  BaseType(BOOL)
OUT: alonbug_fails.p (16, 5): inferred type:  NIL
OUT: alonbug_fails.p (16, 9): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (16, 11): inferred type:  BaseType(BOOL)
OUT: alonbug_fails.p (16, 14): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (17, 9): inferred type:  NIL
OUT: alonbug_fails.p (21, 6): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (21, 6): inferred type:  NIL
OUT: alonbug_fails.p (21, 10): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (21, 12): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (21, 14): inferred type:  BaseType(INT)
OUT: alonbug_fails.p (23, 9): inferred type:  NIL
OUT: alonbug_fails.p (23, 15): inferred type:  BaseType(EVENT)
OUT: 
EXIT: 0
=================================
         Console output          
=================================
OUT: ##################
OUT: Check Failed
OUT: ##################
OUT: 2 distinct states, 1 total transitions, 1 steps max depth
OUT: 
EXIT: 0

=================================
AlonBug_fail.trace
=================================
Safety Error Trace
Trace-Log 0:
<CreateLog> Created Machine Program-0
<StateLog> Machine Program-0 entering State Init
<RaiseLog> Machine Program-0 raised Event ____E
<StateLog> Machine Program-0 exiting State Init

Error:
Zing Assertion failed:
    Expression: tmp_2.bl,
    Comment: (10, 10): Assert failed

Microsoft.Zing.ZingAssertionFailureException: Exception of type 'Microsoft.Zing.ZingAssertionFailureException' was thrown.

Stack trace:
    Program.AnonFun2 (AlonBug_fails.zing, Line 630)
    Program.ReentrancyHelper (AlonBug_fails.zing, Line 415)
    Program.RunHelper (AlonBug_fails.zing, Line 151)
    Program.Run (AlonBug_fails.zing, Line 64)
    Program.Start (AlonBug_fails.zing, Line 42)

